// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

#ifndef PACKIO_CONFIG_H
#define PACKIO_CONFIG_H

#include <boost/asio.hpp>

#if defined(BOOST_ASIO_HAS_CO_AWAIT)
#define PACKIO_HAS_CO_AWAIT BOOST_ASIO_HAS_CO_AWAIT
#endif // defined(BOOST_ASIO_HAS_CO_AWAIT)

#if defined(BOOST_ASIO_HAS_LOCAL_SOCKETS)
#define PACKIO_HAS_LOCAL_SOCKETS BOOST_ASIO_HAS_LOCAL_SOCKETS
#endif // defined(BOOST_ASIO_HAS_LOCAL_SOCKETS)

#if defined(BOOST_ASIO_COMPLETION_TOKEN_FOR)
#define PACKIO_COMPLETION_TOKEN_FOR(e) BOOST_ASIO_COMPLETION_TOKEN_FOR(e)
#else // defined(BOOST_ASIO_COMPLETION_TOKEN_FOR)
#define PACKIO_COMPLETION_TOKEN_FOR(e) typename
#endif // defined(BOOST_ASIO_COMPLETION_TOKEN_FOR)

#if defined(BOOST_ASIO_DEFAULT_COMPLETION_TOKEN)
#define PACKIO_DEFAULT_COMPLETION_TOKEN(e) \
    BOOST_ASIO_DEFAULT_COMPLETION_TOKEN(e)
#else // defined(BOOST_ASIO_DEFAULT_COMPLETION_TOKEN)
#define PACKIO_DEFAULT_COMPLETION_TOKEN(e)
#endif // defined(BOOST_ASIO_DEFAULT_COMPLETION_TOKEN)

#if defined(BOOST_ASIO_DEFAULT_COMPLETION_TOKEN_TYPE)
#define PACKIO_DEFAULT_COMPLETION_TOKEN_TYPE(e) \
    BOOST_ASIO_DEFAULT_COMPLETION_TOKEN_TYPE(e)
#else // defined(BOOST_ASIO_DEFAULT_COMPLETION_TOKEN_TYPE)
#define PACKIO_DEFAULT_COMPLETION_TOKEN_TYPE(e)
#endif // defined(BOOST_ASIO_DEFAULT_COMPLETION_TOKEN_TYPE)

#endif // PACKIO_CONFIG_H
