name: tests

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        conan-current-page: [1, 2, 3, 4, 5, 6]
        conan-total-pages: [6]
        conan-cpu-count: [2]
        os: [ubuntu-22.04]
        include:
          - os: windows-2019
            conan-current-page: 1
            conan-total-pages: 2
            conan-cpu-count: 1
          - os: windows-2019
            conan-current-page: 2
            conan-total-pages: 2
            conan-cpu-count: 1
          - os: windows-2022
            conan-current-page: 1
            conan-total-pages: 2
            conan-cpu-count: 1
          - os: windows-2022
            conan-current-page: 2
            conan-total-pages: 2
            conan-cpu-count: 1
          - os: macos-11.0
            conan-current-page: 1
            conan-total-pages: 1
            conan-cpu-count: 2
    runs-on: ${{ matrix.os }}
    env:
      CONAN_REQUEST_TIMEOUT: 300
      CONAN_CPU_COUNT: ${{ matrix.conan-cpu-count }}
      CONAN_TOTAL_PAGES: ${{ matrix.conan-total-pages }}
      CONAN_CURRENT_PAGE: ${{ matrix.conan-current-page }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: python -m pip install -U "conan<2" conan_package_tools

      - name: Install Ubuntu compilers
        if: matrix.os == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            g++-9 \
            g++-10 \
            g++-11 \
            g++-12 \
            clang-11 \
            clang-12 \
            clang-13 \
            clang-14 \
            libc++-14-dev \
            libc++abi-14-dev

      - name: Build
        if: ${{ !startsWith(matrix.os, 'windows-') }}
        run: python .github/build.py

      - name: Build windows 2019
        if: matrix.os == 'windows-2019'
        env:
          PACKIO_WINDOWS_COMPILER_VERSION: 16
        run: python .github/build.py

      - name: Build windows 2022
        if: matrix.os == 'windows-2022'
        env:
          PACKIO_WINDOWS_COMPILER_VERSION: 17
        run: python .github/build.py
  docs:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Install doxygen
        run: sudo apt-get install -y doxygen

      - name: Build documentation
        run: doxygen

      - name: Deploy
        if: github.ref == 'refs/heads/master'
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs
          CLEAN: true
